directories:
  output: dist-electron
  buildResources: build
appId: com.ebs.keymanagement
productName: EBS Key Management
compression: store
nodeGypRebuild: false
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - package.json
extraResources: []
mac:
  category: public.app-category.business
  target: dir
win:
  target: dir
linux:
  target: dir
electronVersion: 37.2.6
